import { Car, Booking } from '../types';

export const mockData = {
  cars: [
    {
      id: '1',
      name: 'Toyota Camry 2023',
      brand: 'Toyota',
      model: 'Camry',
      year: 2023,
      category: 'Economy',
      price_per_day: 45,
      fuel_type: 'Hybrid',
      transmission: 'Automatic',
      seats: 5,
      image: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=400',
      description: 'Reliable and fuel-efficient sedan perfect for business trips and daily commuting.',
      features: ['Bluetooth', 'Backup Camera', 'Cruise Control', 'Apple CarPlay'],
      available: true,
      location: 'Downtown',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '2',
      name: 'BMW X5 2023',
      brand: 'BMW',
      model: 'X5',
      year: 2023,
      category: 'Luxury',
      price_per_day: 125,
      fuel_type: 'Gasoline',
      transmission: 'Automatic',
      seats: 7,
      image: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=400',
      description: 'Premium luxury SUV with advanced features and exceptional comfort.',
      features: ['Leather Seats', 'Navigation', 'Premium Audio', 'Panoramic Sunroof'],
      available: true,
      location: 'Airport',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '3',
      name: 'Ford Mustang 2023',
      brand: 'Ford',
      model: 'Mustang',
      year: 2023,
      category: 'Sports',
      price_per_day: 85,
      fuel_type: 'Gasoline',
      transmission: 'Manual',
      seats: 4,
      image: 'https://images.unsplash.com/photo-1547744152-14d985cb937e?w=400',
      description: 'Iconic American muscle car delivering thrilling performance and style.',
      features: ['Sport Mode', 'Premium Sound', 'Performance Tires', 'Racing Stripes'],
      available: true,
      location: 'Downtown',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '4',
      name: 'Tesla Model 3 2023',
      brand: 'Tesla',
      model: 'Model 3',
      year: 2023,
      category: 'Electric',
      price_per_day: 95,
      fuel_type: 'Electric',
      transmission: 'Automatic',
      seats: 5,
      image: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=400',
      description: 'Revolutionary electric sedan with autopilot and cutting-edge technology.',
      features: ['Autopilot', 'Supercharger Access', 'Premium Connectivity', 'Glass Roof'],
      available: true,
      location: 'Tech District',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '5',
      name: 'Jeep Wrangler 2023',
      brand: 'Jeep',
      model: 'Wrangler',
      year: 2023,
      category: 'SUV',
      price_per_day: 75,
      fuel_type: 'Gasoline',
      transmission: 'Automatic',
      seats: 5,
      image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=400',
      description: 'Rugged off-road capable SUV perfect for adventure seekers.',
      features: ['4WD', 'Removable Roof', 'Skid Plates', 'Rock Rails'],
      available: true,
      location: 'Adventure Center',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '6',
      name: 'Mercedes-Benz C-Class 2023',
      brand: 'Mercedes-Benz',
      model: 'C-Class',
      year: 2023,
      category: 'Luxury',
      price_per_day: 110,
      fuel_type: 'Gasoline',
      transmission: 'Automatic',
      seats: 5,
      image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?w=400',
      description: 'Elegant luxury sedan with premium comfort and advanced safety features.',
      features: ['MBUX Infotainment', 'LED Headlights', 'Premium Interior', 'Driver Assistance'],
      available: false,
      location: 'Luxury Hub',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '7',
      name: 'Honda Civic 2023',
      brand: 'Honda',
      model: 'Civic',
      year: 2023,
      category: 'Compact',
      price_per_day: 35,
      fuel_type: 'Gasoline',
      transmission: 'CVT',
      seats: 5,
      image: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=400',
      description: 'Efficient and reliable compact car ideal for city driving.',
      features: ['Honda Sensing', 'Touchscreen', 'Fuel Efficient', 'Spacious Interior'],
      available: true,
      location: 'City Center',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    },
    {
      id: '8',
      name: 'Audi Q7 2023',
      brand: 'Audi',
      model: 'Q7',
      year: 2023,
      category: 'Luxury',
      price_per_day: 140,
      fuel_type: 'Gasoline',
      transmission: 'Automatic',
      seats: 7,
      image: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=400',
      description: 'Premium luxury SUV with three rows and advanced technology.',
      features: ['Virtual Cockpit', 'Quattro AWD', 'Prestige Package', 'Bang & Olufsen Audio'],
      available: true,
      location: 'Premium Lot',
      created_at: '2023-01-01T00:00:00Z',
      updated_at: '2023-01-01T00:00:00Z'
    }
  ] as Car[],

  bookings: [
    {
      id: '1',
      car_id: '1',
      customer_name: 'John Smith',
      customer_email: 'john.smith@email.com',
      customer_phone: '+1-555-0123',
      start_date: '2023-12-01',
      end_date: '2023-12-05',
      total_price: 180,
      status: 'confirmed' as const,
      pickup_location: 'Downtown',
      dropoff_location: 'Downtown',
      special_requests: 'GPS navigation needed',
      created_at: '2023-11-15T00:00:00Z',
      updated_at: '2023-11-15T00:00:00Z'
    }
  ] as Booking[],

  categories: [
    'Economy',
    'Compact',
    'SUV',
    'Luxury',
    'Sports',
    'Electric'
  ],

  locations: [
    'Downtown',
    'Airport',
    'Tech District',
    'Adventure Center',
    'Luxury Hub',
    'City Center',
    'Premium Lot'
  ]
};